# Generated by Django 3.2 on 2022-08-03 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название договра', verbose_name='Название договра')),
                ('number', models.TextField(help_text='Введите номер договра', verbose_name='Номер договра')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(help_text='Введите дату окончания договра', verbose_name='Дата окончания')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='Файл договора')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Куратор договора')),
                ('partner', models.ForeignKey(help_text='Вторая сторона по договору', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.partner', verbose_name='Контрагент')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
