# Generated by Django 3.2 on 2022-08-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partner',
            field=models.ForeignKey(help_text='Вторая сторона по договору', on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='contracts.partner', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(help_text='Введите дату начала договра', verbose_name='Дата начала'),
        ),
        migrations.CreateModel(
            name='UserContraсts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Collaborator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь договора')),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Contract', to='contracts.contract', verbose_name='Договор')),
            ],
        ),
    ]
