# Generated by Django 3.2 on 2022-08-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20220805_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontraсts',
            old_name='Collaborator',
            new_name='collaborator',
        ),
    ]
