# Generated by Django 3.2 on 2022-08-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20220805_1515'),
        ('userprofile', '0002_alter_userprofile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='contracts.partner', verbose_name='Компания'),
        ),
    ]
